### ISSUE TITLE
Pagination for more character

### ISSUE THREAD

**Issue by Push9828** [Push9828/Rick-and-Morty-API#1]

**Comment by devTeaa** [comment]
Hi @Push9828 can you tell me more what kind pagination do you want? I help on this issue

**Comment by Push9828** [comment]
I need to add more than 20 characters but the API permits 20 per page... I need the pagination so all characters can be visible on the website...

**Comment by devTeaa** [comment]
do you have any specific design? Does a simple next and back is good enough? Or do I need to make it with page numbers?

**Comment by Push9828** [comment]
page-no is fine... Stick with the website colors

**Comment by devTeaa** [comment]
is this good enough @Push9828 ?
![Capture5](https://user-images.githubusercontent.com/38621036/94836132-d1d6db80-043c-11eb-87a5-4ebe87e188c1.gif)

**Comment by Push9828** [comment]
Nice can you make it a little smaller.

**Comment by devTeaa** [comment]
Hi @Push9828 I have created a PR with the lasted update to change the size

**Comment by devTeaa** [comment]
You can close this issue if it's done @Push9828 , and thanks for the merge

**Comment by bogodars** [comment]
@devTeaa can you please suggest the way of controlling quantity of array items on the page with pagination instead of default 20 ?
